### ISSUE TITLE
bitmap.c block corrupt ERROR

### ISSUE THREAD

**Issue by thomasgoehler** [moononournation/arduino-nofrendo#2]
Hi moononournation,
i have build your project which you published on "instructables".
Compiling and uploading works without problems.
When I restart the TTGO T8 v1.7 I only get a grey screen and on the serial console it shows me the following error:

addr: 0x3FFCF944, size: 61443, line 86 of C:\Users\thomas\Documents\Arduino\libraries\arduino-nofrendo-master\src\bitmap.c -- block corrupt

can you fix it?

**Comment by moononournation** [comment]
the log "bitmap.c -- block corrupt" is fine. It is nofrendo normal debug message and you can see this message means nofrendo runs well.
The grey screen probably caused by the LCD connection. To narrow down the problem, you can first try to run the Arduino_GFX PDQgraphictest example for testing the display only.

**Comment by lordherp** [comment]
I'm having the same problem, display is white and the "block corrupt" message. I already verified my display is working correctly.  Is there any way to debug this?

**Comment by moononournation** [comment]
Can you run Arduino_GFX PDQgraphictest example correctly?

**Comment by lordherp** [comment]
Yes. 
![IMG_1696 (Small)](https://user-images.githubusercontent.com/67761173/195538477-969dbd54-c7b6-441e-bc61-eb82fd923d08.JPG)

**Comment by moononournation** [comment]
sorry, nes cannot display in 160x128 resolution
